#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

canCompile || exit 0    # Dynamic code

restore0Dir
touch slipSTL.foam

runApplication blockMesh
runApplication moveDynamicMesh

runApplication checkMesh -writeFields '(aspectRatio cellAspectRatio cellVolume cellVolumeRatio nonOrthoAngle skewness)'
runApplication postProcess -funcs '(fieldMinMax_aspectRatio fieldMinMax_cellAspectRatio fieldMinMax_cellVolume fieldMinMax_cellVolumeRatio fieldMinMax_nonOrthoAngle fieldMinMax_skewness)'
#------------------------------------------------------------------------------
